name: ci

on:
  push:
    branches: main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0

      # Run GitVersion
      - name: Determine Semantic Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.6
      
      # Log in to dockerhub
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push container to dockerhub
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: azureiotgbb/iot-edge-dev-container, azureiotgbb/iot-edge-dev-container:buster-slim
