name: ci

on:
  push:
    branches: main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0

      # Log in to dockerhub
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

                -
      # Build and push container to dockerhub
      - uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./.devcontainer/Dockerfile
          push: true
          tags: |
            azureiotgbb/iot-edge-dev-container:latest
            azureiotgbb/iot-edge-dev-container:buster-slim
